### ISSUE TITLE
p1xbraten detection broken on certain servers

### ISSUE THREAD

**Issue by Jed-** [sauerbraten/p1xbraten#28]
The popular "RUGBY iCTF" server recently switched to a new method to calculate ping on the server side.
Incoming `N_PING` and `N_CLIENTPING` messages are discarded so the extra pings never reach other clients, breaking p1xbraten detection as a result.

I would suggest using `N_SWITCHMODEL` with a specific value to signal that the client is using p1xbraten instead of relying on ping. That would also eliminate the need for a confidence level.

**Comment by sauerbraten** [comment]
Mhmm, how do you suggest this to work without becoming incompatible with vanilla? I guess I could send a special value, then change back to the correct one? What would the effects be on vanilla clients? From the code, it appears that they would be rendered in the vanilla user's playermodel for the duration of the out-of-range value?

I like the idea, I'll see if I can make it work. Thanks for the hint!

**Comment by Jed-** [comment]
You could try sending a first `N_SWITCHMODEL` with the special value,
followed by a second one with the original value.
You should be able to put them in the same packet:
`N_SWITCHMODEL SPECIAL_VAL N_SWITCHMODEL ORIG_VAL`

If the messages are sent at the same time, they will also be processed by
the clients at the same time so players shouldn't notice anything.
Instead of doing it at regular intervals, it should only be necessary when
joining a server or when another client joins.
