### ISSUE TITLE
"fullbright player models" setting bug

### ISSUE THREAD

**Issue by xXRaptorSc0pezXx** [sauerbraten/p1xbraten#65]
With p1x the fullbright player models setting doesn't give you any indicator that one of the options is selected. For example, with the vanilla HUD when you select one of the options an indicator (a square with a circle in it) to the left of the word will turn green (specifically the circle will turn green), letting you know that option is selected. With the p1x HUD all the options already have that indicator next to them colored green by default so you cannot tell which is selected.

**Comment by sauerbraten** [comment]
thanks for reporting this bug!

I noticed this already and fixed it in https://github.com/sauerbraten/p1xbraten/commit/b2a35e8bc530ee1fd3170eff0ae00378fdf48391. it will be part of the next release.
