### ISSUE TITLE
Add player character icons (scoreboard)

### ISSUE THREAD

**Issue by xXRaptorSc0pezXx** [sauerbraten/p1xbraten#66]
Player character icons no longer appear on the scoreboard to the left of player's usernames when using p1xbraten. Please add an option to enable these.

**Comment by sauerbraten** [comment]
I won't. but I want to make using the p1xbraten scoreboard optional, see https://github.com/sauerbraten/p1xbraten/issues/67.

**Comment by xXRaptorSc0pezXx** [comment]
How come? I really enjoy the extra data of the p1xbraten scoreboard but miss the little pictures :(
