### ISSUE TITLE
EAC openid server ? 

### ISSUE THREAD

**Issue by anass114** [sauerbraten/p1xbraten#69]
Hi, 

You have mentionned really quickly in how you managed to simulate eos_login stuff...

I tryed to do same thing as you did on laravel : 

`  return response(json_encode(array("a" => "userid","b" => "nameid" ))
        )->header('authorization', 'Bearer userid)->header('Content-Type', 'application/json');`
        
 I do have the authorization bearer that matches the username as intented. But I always get error 7000. 
 
 Thanks for your help

**Comment by sauerbraten** [comment]
Here's my whole Go code:

```go
package main

import (
	"fmt"
	"log"
	"net/http"
	"strings"
)

func main() {
	http.HandleFunc("/echotoken", func(w http.ResponseWriter, r *http.Request) {
		// get token from header
		auth := r.Header.Get("authorization")
		if auth == "" || (!strings.HasPrefix(auth, "Bearer ") && !strings.HasPrefix(auth, "bearer ")) {
			w.WriteHeader(http.StatusBadRequest)
			fmt.Fprintln(w, "authorization header missing or malformed")
			return
		}
		token := auth[len("bearer "):]
		// echo it as id field in a JSON object
		w.Header().Add("content-type", "application/json")
		fmt.Fprintln(w, `{"id":"`+token+`"}`)
	})

	log.Println(http.ListenAndServe(":8080", nil))
}
```

So you have to extract the auth token from the headers and play it back in the body as "id" field in a JSON object. You don't need to set an Authorization header in the response. I believe this, or something close to it, would do the trick:

```php
    // todo: get token from request's Autorization header
    // the header value will be `Bearer xxxyyyzzz` and you have to extract the `xxyyzz` part into a $token variable.
    return response(json_encode(array("id" => $token )) )->header('Content-Type', 'application/json');
```

I can't help you more than that, I don't know PHP/Laravel.

**Comment by anass114** [comment]
Thanks, 

I tryed your script and worked on first try. Can't understand why it didn't work on laravel. I tryed with/without the authorization header on response. Anyway, I will debug that later.
