### ISSUE TITLE
Distribute separate Windows releases without anticheat

### ISSUE THREAD

**Issue by Calinou** [sauerbraten/p1xbraten#74]
I'm only interested in playing on servers that don't require the anticheat, yet the Windows installer requires installing the EAC service on the system. Is there a way this could be done without having to compile from source?

**Edit:** I found a way with 7-zip installed:

- Run this in a command prompt in the folder where you've downloaded the installer:

```bash
7z x p1xbraten_setup_8.2.0.exe
```

- Drag `p1xbraten.bat` and the `bin64` folder to your Sauerbraten installation. You can remove `bin64/start_protected_game.exe` as it's not needed.

**Comment by sauerbraten** [comment]
Nice workaround, seems like less work than it would take me to compile two Windows binaries, write another installer build script, run that as part of packaging, etc. I'll link to it when the next person asks :D
